name: Test React App
on: push
jobs:
  test_my_react_app: windows-latest
  steps:
    - name: Get repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: npm ci
    - name: Test application
      run: npm run test